// <auto-generated />
using System;
using BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240122070114_FVenue_Init")]
    partial class FVenue_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginVia")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SaltPassword")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2002, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2024, 1, 22, 14, 1, 14, 363, DateTimeKind.Local).AddTicks(7464),
                            Email = "huynhduy20042002@gmail.com",
                            FirstName = "Duy",
                            Gender = true,
                            HashPassword = "F01EA7AD38B8C0C21695A1511EBC8E9C10F868903D6DA854C495E775EF893DD874AB64035542195866868577EFEC40056B4EBEA8678BE1F7D86B4EFD15F3482E",
                            Image = "~/Image/Administrator/SuperAdmin.jpg",
                            IsEmailConfirmed = false,
                            LastName = "Lê Tự Huỳnh",
                            LastUpdateDate = new DateTime(2024, 1, 22, 14, 1, 14, 363, DateTimeKind.Local).AddTicks(7475),
                            LoginVia = 1,
                            PhoneNumber = "0432247262",
                            RoleId = 1,
                            SaltPassword = new byte[] { 43, 87, 57, 53, 96, 187, 254, 124, 246, 37, 241, 32, 121, 204, 219, 221, 108, 128, 164, 220, 153, 198, 245, 48, 98, 204, 89, 250, 144, 248, 10, 93, 218, 88, 249, 8, 71, 80, 211, 163, 26, 87, 212, 56, 238, 45, 54, 214, 250, 173, 157, 78, 184, 147, 74, 147, 81, 115, 78, 126, 252, 68, 165, 47 },
                            Status = true
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Địa điểm giải trí"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ẩm thực"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thức uống"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Giải trí về đêm"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Đà Nẵng"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Việt Nam"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Hải Châu"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Cẩm Lệ"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Liên Chiểu"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Thanh Khê"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Sơn Trà"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Name = "Ngũ Hành Sơn"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "VenueManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Địa điểm công cộng"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LowerPrice")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("UpperPrice")
                        .HasColumnType("real");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("WardId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Đỉnh Bàn Cờ",
                            GeoLocation = "16.1203775657414,108.27607464602765",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipNTJk8DvgrCr2RyeTfKzedNpx4o4LOO06rSXSVQ=w408-h272-k-no",
                            LowerPrice = 0f,
                            Name = "Đỉnh Bàn Cờ",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "",
                            UpperPrice = 0f,
                            WardId = 41
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Cầu Rồng",
                            GeoLocation = "16.061233815354754,108.22749003748194",
                            Image = "https://static.vinwonders.com/2022/04/cau-rong-da-nang-1-1.jpg",
                            LowerPrice = 0f,
                            Name = "Cầu Rồng",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Nguyễn Văn Linh",
                            UpperPrice = 0f,
                            WardId = 10
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Cầu Sông Hàn",
                            GeoLocation = "16.072169332052994,108.22683626631773",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipPR0yFg71ydHaR3xXbbMApGnySOSmF5IBCXeWmc=w408-h306-k-no",
                            LowerPrice = 0f,
                            Name = "Cầu Sông Hàn",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Lê Duẩn",
                            UpperPrice = 0f,
                            WardId = 3
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Cầu Nguyễn Văn Trỗi",
                            GeoLocation = "16.05112083078253,108.22907016535224",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipNTJk8DvgrCr2RyeTfKzedNpx4o4LOO06rSXSVQ=w408-h272-k-no",
                            LowerPrice = 0f,
                            Name = "Cầu Nguyễn Văn Trỗi",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Nguyễn Văn Thoại",
                            UpperPrice = 0f,
                            WardId = 37
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Cầu Tình Yêu",
                            GeoLocation = "16.1203775657414,108.27607464602765",
                            Image = "https://ik.imagekit.io/tvlk/blog/2023/08/cau-tinh-yeu-da-nang-2.jpg?tr=dpr-2",
                            LowerPrice = 0f,
                            Name = "Cầu Tình Yêu",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Trần Hưng Đạo",
                            UpperPrice = 0f,
                            WardId = 37
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Chợ đêm Sơn Trà",
                            GeoLocation = "16.06160809465977,108.23198549515325",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipOy3zJV9uGKBOAvqq7JfD47k-pJ3pJdX08AsFqt=w493-h240-k-no",
                            LowerPrice = 0f,
                            Name = "Chợ đêm Sơn Trà",
                            OpenTime = new DateTime(2024, 1, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Mai Hắc Đế",
                            UpperPrice = 0f,
                            WardId = 37
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Tượng Cá Chép hóa Rồng",
                            GeoLocation = "16.062920294590672,108.22982572398891",
                            Image = "https://lh3.googleusercontent.com/p/AF1QipOsja5mY4FutBBksUpPGk7xtTfT2LONbebEZsIY=s1360-w1360-h1020",
                            LowerPrice = 0f,
                            Name = "Tượng Cá Chép hóa Rồng",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Trần Hưng Đạo",
                            UpperPrice = 0f,
                            WardId = 37
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Biển Mỹ Khê",
                            GeoLocation = "16.05658360521848,108.24744872398874",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipPgpkvaWeKD9pejm2Org-oEx-SWXLyGH_qSUneu=w426-h240-k-no",
                            LowerPrice = 0f,
                            Name = "Biển Mỹ Khê",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Võ Nguyên Giáp",
                            UpperPrice = 0f,
                            WardId = 42
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Công viên 29/3",
                            GeoLocation = "16.1203775657414,108.27607464602765",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipNPIejeI79llYfMNFnAdGnaBKNCt6G4Fwo6Q2tM=w426-h240-k-no",
                            LowerPrice = 0f,
                            Name = "Công viên 29/3",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "23 Nguyễn Tri Phương",
                            UpperPrice = 0f,
                            WardId = 33
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Bãi tắm Phạm Văn Đồng",
                            GeoLocation = "16.07338349250206,108.24686918822724",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipMeJRsg8S_9w2m3KaBuovV_87uF5IsM8eubr1vY=w408-h272-k-no",
                            LowerPrice = 0f,
                            Name = "Bãi tắm Phạm Văn Đồng",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Võ Nguyên Giáp",
                            UpperPrice = 0f,
                            WardId = 37
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Bãi đá Obama",
                            GeoLocation = "16.09979446980971,108.30122137705182",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipNZY0gLKkyBp6SeM7KEMPadCos2lOCHNwWhAIvI=w408-h354-k-no",
                            LowerPrice = 0f,
                            Name = "Bãi đá Obama",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "",
                            UpperPrice = 0f,
                            WardId = 41
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Chân cầu Thuận Phước.",
                            GeoLocation = "16.095265292762104,108.22045666551136",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipP4U2h2NuO5IC4xNdkPtRO0hTpg-kRLkUo1RuYY=w408-h271-k-no",
                            LowerPrice = 0f,
                            Name = "Chân cầu Thuận Phước.",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "Lê Đức Thọ",
                            UpperPrice = 0f,
                            WardId = 39
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Chợ đêm Helio",
                            GeoLocation = "16.037429266613337,108.22457798825782",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipOT5qP5cG4MJAC6pFlFwbNhpTJRFBKDZi16uD79=w408-h306-k-no",
                            LowerPrice = 0f,
                            Name = "Chợ đêm Helio",
                            OpenTime = new DateTime(2024, 1, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "2 Tháng 9",
                            UpperPrice = 0f,
                            WardId = 5
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 1,
                            CloseTime = new DateTime(2024, 1, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đây là mô tả về Rạn Nam Ô",
                            GeoLocation = "16.117981036882956,108.13000619993463",
                            Image = "https://lh5.googleusercontent.com/p/AF1QipPLWohOtxqRtG8sPz8yFNmPk7UA_QovxpBtwifr=w408-h305-k-no",
                            LowerPrice = 0f,
                            Name = "Rạn Nam Ô",
                            OpenTime = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Street = "",
                            UpperPrice = 0f,
                            WardId = 21
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.VenueSubCategory", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("VenueId", "SubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("VenueSubCategories");
                });

            modelBuilder.Entity("BusinessObjects.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictId = 1,
                            Name = "Bình Hiên"
                        },
                        new
                        {
                            Id = 2,
                            DistrictId = 1,
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = 3,
                            DistrictId = 1,
                            Name = "Hải Châu 1"
                        },
                        new
                        {
                            Id = 4,
                            DistrictId = 1,
                            Name = "Hải Châu 2"
                        },
                        new
                        {
                            Id = 5,
                            DistrictId = 1,
                            Name = "Hoà Cường Bắc"
                        },
                        new
                        {
                            Id = 6,
                            DistrictId = 1,
                            Name = "Hoà Cường Nam"
                        },
                        new
                        {
                            Id = 7,
                            DistrictId = 1,
                            Name = "Hoà Thuận Đông"
                        },
                        new
                        {
                            Id = 8,
                            DistrictId = 1,
                            Name = "Hoà Thuận Tây"
                        },
                        new
                        {
                            Id = 9,
                            DistrictId = 1,
                            Name = "Nam Dương"
                        },
                        new
                        {
                            Id = 10,
                            DistrictId = 1,
                            Name = "Phước Ninh"
                        },
                        new
                        {
                            Id = 11,
                            DistrictId = 1,
                            Name = "Thạch Thang"
                        },
                        new
                        {
                            Id = 12,
                            DistrictId = 1,
                            Name = "Thanh Bình"
                        },
                        new
                        {
                            Id = 13,
                            DistrictId = 1,
                            Name = "Thuận Phước"
                        },
                        new
                        {
                            Id = 14,
                            DistrictId = 2,
                            Name = "Hoà An"
                        },
                        new
                        {
                            Id = 15,
                            DistrictId = 2,
                            Name = "Hoà Phát"
                        },
                        new
                        {
                            Id = 16,
                            DistrictId = 2,
                            Name = "Hoà Thọ Đông"
                        },
                        new
                        {
                            Id = 17,
                            DistrictId = 2,
                            Name = "Hoà Thọ Tây"
                        },
                        new
                        {
                            Id = 18,
                            DistrictId = 2,
                            Name = "Hoà Xuân"
                        },
                        new
                        {
                            Id = 19,
                            DistrictId = 2,
                            Name = "Khuê Trung"
                        },
                        new
                        {
                            Id = 20,
                            DistrictId = 3,
                            Name = "Hoà Hiệp Bắc"
                        },
                        new
                        {
                            Id = 21,
                            DistrictId = 3,
                            Name = "Hoà Hiệp Nam"
                        },
                        new
                        {
                            Id = 22,
                            DistrictId = 3,
                            Name = "Hoà Khánh Bắc"
                        },
                        new
                        {
                            Id = 23,
                            DistrictId = 3,
                            Name = "Hoà Khánh Nam"
                        },
                        new
                        {
                            Id = 24,
                            DistrictId = 3,
                            Name = "Hoà Minh"
                        },
                        new
                        {
                            Id = 25,
                            DistrictId = 4,
                            Name = "An Khê"
                        },
                        new
                        {
                            Id = 26,
                            DistrictId = 4,
                            Name = "Hòa Khê"
                        },
                        new
                        {
                            Id = 27,
                            DistrictId = 4,
                            Name = "Thanh Khê Đông"
                        },
                        new
                        {
                            Id = 28,
                            DistrictId = 4,
                            Name = "Thanh Khê Tây"
                        },
                        new
                        {
                            Id = 29,
                            DistrictId = 4,
                            Name = "Xuân Hà"
                        },
                        new
                        {
                            Id = 30,
                            DistrictId = 4,
                            Name = "Tam Thuận"
                        },
                        new
                        {
                            Id = 31,
                            DistrictId = 4,
                            Name = "Tân Chính"
                        },
                        new
                        {
                            Id = 32,
                            DistrictId = 4,
                            Name = "Chính Gián"
                        },
                        new
                        {
                            Id = 33,
                            DistrictId = 4,
                            Name = "Thạc Gián"
                        },
                        new
                        {
                            Id = 34,
                            DistrictId = 4,
                            Name = "Vĩnh Trung"
                        },
                        new
                        {
                            Id = 35,
                            DistrictId = 5,
                            Name = "An Hải Bắc"
                        },
                        new
                        {
                            Id = 36,
                            DistrictId = 5,
                            Name = "An Hải Đông"
                        },
                        new
                        {
                            Id = 37,
                            DistrictId = 5,
                            Name = "An Hải Tây"
                        },
                        new
                        {
                            Id = 38,
                            DistrictId = 5,
                            Name = "Mân Thái"
                        },
                        new
                        {
                            Id = 39,
                            DistrictId = 5,
                            Name = "Nại Hiên Đông"
                        },
                        new
                        {
                            Id = 40,
                            DistrictId = 5,
                            Name = "Phước Mỹ"
                        },
                        new
                        {
                            Id = 41,
                            DistrictId = 5,
                            Name = "Thọ Quang"
                        },
                        new
                        {
                            Id = 42,
                            DistrictId = 6,
                            Name = "Hoà Hải"
                        },
                        new
                        {
                            Id = 43,
                            DistrictId = 6,
                            Name = "Hoà Quý"
                        },
                        new
                        {
                            Id = 44,
                            DistrictId = 6,
                            Name = "Khuê Mỹ"
                        },
                        new
                        {
                            Id = 45,
                            DistrictId = 6,
                            Name = "Mỹ An"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Account", b =>
                {
                    b.HasOne("BusinessObjects.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjects.Models.City", b =>
                {
                    b.HasOne("BusinessObjects.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BusinessObjects.Models.District", b =>
                {
                    b.HasOne("BusinessObjects.Models.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BusinessObjects.Models.SubCategory", b =>
                {
                    b.HasOne("BusinessObjects.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjects.Models.Venue", b =>
                {
                    b.HasOne("BusinessObjects.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("BusinessObjects.Models.VenueSubCategory", b =>
                {
                    b.HasOne("BusinessObjects.Models.SubCategory", "SubCategory")
                        .WithMany("VenueSubCategories")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Models.Venue", "Venue")
                        .WithMany("VenueSubCategories")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BusinessObjects.Models.Ward", b =>
                {
                    b.HasOne("BusinessObjects.Models.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("BusinessObjects.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BusinessObjects.Models.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("BusinessObjects.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("BusinessObjects.Models.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("BusinessObjects.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BusinessObjects.Models.SubCategory", b =>
                {
                    b.Navigation("VenueSubCategories");
                });

            modelBuilder.Entity("BusinessObjects.Models.Venue", b =>
                {
                    b.Navigation("VenueSubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
